ruby_on_rails/private-events/config/routes.rb
Rails.application.routes.draw do
  get		'/signin',                to: 'sessions#new'
  post		'/signin',				      to: 'sessions#create'
  delete	'/signout',				      to: 'sessions#destroy'
  resources	:users,					      only: [:show, :new, :create]
  resources :events,				      only: [:index, :show, :new, :create] do
  	resources :invitations,			  only: [:new, :create]
  	get	'/attend/:user_id',		  to: 'attendances#create'
  	delete	'/unattend/:user_id',	to: 'attendances#destroy'
  end
  resources :invitations,			    only: [:index, :show, :destroy]
end

ruby_on_rails/private-events/app/models/user.rb
class User < ApplicationRecord
	has_many :created_events, class_name: "Event", foreign_key: :creator_id
	
	has_many :created_invitations, class_name: "Invitation", foreign_key: :inviter_id
	has_many :received_invitations, class_name: "Invitation", foreign_key: :invitee_id

	# Thanks @alexcorremans!  This method requires no join model, check the schema
	has_and_belongs_to_many :attended_events, # Association Name
		class_name: "Event", # Other model's class name, defaults like 'AttendedEvents'
		join_table: :attended_events_attendees, # Join table, must be alphabetized, would be like 'attended_events_users' by default
		foreign_key: :attendee_id, # Name of the column this model's id should be found in, defaults to this class name
		association_foreign_key: :attended_event_id # Name of the column the associated model's key should be taken from, defaults like 'event_id' in this case

	validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 32 }

	def previous_events
		attended_events.where ["date < ?", DateTime.now]
	end

	def upcoming_events
		attended_events.where ["date > ?", DateTime.now]
	end

	def all_events
		(created_events + attended_events).uniq
	end
end

ruby_on_rails/private-events/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "New account successfully created!"
      session[:user_id] = @user.id
  		redirect_to user_path(@user)
  	else
  		flash.now[:failure] = "There was a problem creating this user account."
  		render :new
  	end
  end

  def show
  	@user = User.find( params[:id] )
    @created_events = @user.created_events.order(date: :desc)
  end

  private
  	def user_params
  		params.require(:user).permit(:name)
  	end
end

ruby_on_rails/private-events/app/helpers/users_helper.rb
module UsersHelper
end

ruby_on_rails/private-events/app/views/users/_errors.html.erb
<ul>
	<% @user.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
</ul>

ruby_on_rails/private-events/app/views/users/new.html.erb
<%= render 'errors' if @user.errors.any? %>
<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit %>
<% end %>

ruby_on_rails/private-events/app/views/users/show.html.erb
<h1>Account Page of <%= @user.name %></h1>
<hr>
<% if @user.created_events.any? %>
	<h2>Created Events</h2>
	<% @created_events.each do |event| %>
		<h3><%= link_to event.name, event_path( event ) %></h3>
		<% unless event.date.nil? %>
			<% if event.date.past? %>
				<h4>Hosted on <%= event.date %></h4>
			<% else %>
				<h4>Hosting on <%= event.date %></h4>
			<% end %>
		<% end %>
	<% end %>
<% end %>
<% if @user.upcoming_events.any? %>
	<h2>Upcoming Events</h2>
	<% @user.upcoming_events.each do |event| %>
		<h3><%= link_to event.name, event_path( event ) %></h3>
		<h4>
			<% if hosting? event %>
				You are hosting this event
			<% else %>
				Hosted by <%= link_to event.creator.name, user_path( event.creator ) %>
			<% end %>
			<% unless event.date.nil? %>
				 on <%= event.date %>
			<% end %>
		</h4>
	<% end %>
<% end %>
<% if @user.previous_events.any? %>
	<h2>Previous_Events</h2>
	<% @user.previous_events.each do |event| %>
		<h3><%= link_to event.name, event_path( event ) %></h3>
		<h4>
			<% if hosting? event %>
				You hosted this event
			<% else %>
				Hosted by <%= link_to event.creator.name, user_path( event.creator ) %>
			<% end %>
			<% unless event.date.nil? %>
				 on <%= event.date %>
			<% end %>
		</h4>
	<% end %>
<% end %>